### ISSUE TITLE
InteractiveConsoleApplication

### ISSUE THREAD

**Issue by klashagel** [jamie-davis/ConsoleTools#10]
Loving this project, best i found of the of the commandline parser i investigated. In the interactiveconsoleapplication sample crashes when one enters a empty command line. Any ideas how to fix this.

**Comment by jamie-davis** [comment]
Hi @klashagel 

Thanks for reporting this, I can't believe I've never spotted the problem. Luckily it was a simple fix. If you take version 1.3.2 of the library, the problem should be gone.

If possible, would you please let me know if the release solves your issue?

Thanks,
Jamie.

**Comment by klashagel** [comment]
Like a charm, thanks for great support

Best regards
Klas
