### ISSUE TITLE
Multi-word commands help with In

### ISSUE THREAD

**Issue by klashagel** [jamie-davis/ConsoleTools#11]
Trying to get help text with Multi-Word commands to work. I can see in you excellent manual and im not sure if its not working or by design for a ConsoleApplication 

If i do as in the manual , use List<string> instead of string , like
```
  [InteractiveCommand]
    [Description("Display command help")]
    public class HelpCommand
    {
        [Positional(DefaultValue = null)]
        [Description("The command for which to display help")]
        public List<string> Command { get; set; }
    }
```
the InteractiveHelpCommand furnction does not allow arrays as the HelpCommand does

```
  protected override void Initialise()
        {

           HelpOption<Options>(o => o.Help);
            InteractiveHelpCommand<HelpCommand>(h => h.Command);
            base.Initialise();
        }
```
Is this a bug or by design, or am i doing somethging wrong

**Comment by jamie-davis** [comment]
I'll look into this later on, but there was a bug with the non-interactive help command when I introduced command keywords. It's possible that the fix for that did not work on interactive help. I'll report back when I've done some investigating.

**Comment by jamie-davis** [comment]
@klashagel you are certainly helping me improve ConsoleToolkit!

This help issue is an error on my part - I neglected to update help support in interactive only console apps when I added keywords. I've deployed version 1.3.3 to nuget with a fix, so if you update to the latest you should be good to go.

Could you let me know how you get on?

Thanks,
Jamie.

**Comment by klashagel** [comment]
Works beutifully, thanks
